# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [57]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]


In [58]:
# Method 2
c_arr = np.random.rand(2,3,5)
print(c_arr)

[[[0.95494326 0.9644674  0.18708757 0.07089828 0.07984287]
  [0.66420935 0.50439704 0.19379635 0.89747129 0.4606857 ]
  [0.93479168 0.3787675  0.86899303 0.02665233 0.63118928]]

 [[0.53453873 0.98016601 0.53080874 0.37558272 0.53939516]
  [0.89679725 0.37388539 0.70901438 0.75131484 0.2612758 ]
  [0.74471892 0.63120401 0.37381475 0.1244816  0.66594654]]]


In [59]:
# Method 3.1
b_arr = [np.random.randint(0,100) for i in range(30)]
b_array = np.array(b_arr).reshape(2,3,5)
print(b_array)

[[[65 18 56 54 55]
  [75 36 66 87 79]
  [85 28 77 10 66]]

 [[70 97  2 72 66]
  [61 54 19 15 34]
  [41  0 66 15 18]]]


In [60]:
# Method 3.2
d_arr =np.random.randint(0,100, size=(2,3,5))
print(d_arr)

[[[22 76 77 57 26]
  [10 59 23 91 53]
  [52 34 50 61 97]]

 [[65 53 97 25 70]
  [16 98 18 60 91]
  [90 62 74 14 45]]]


[[[0.39076996 0.15615743 0.01015129 0.69143001 0.07136375]
  [0.79574913 0.11824176 0.7307947  0.39963132 0.17387422]
  [0.02978897 0.42063009 0.42877456 0.13421395 0.3911829 ]]

 [[0.78475941 0.76468082 0.38141975 0.30093008 0.40751264]
  [0.5832881  0.7971327  0.30290598 0.9349324  0.13448457]
  [0.67808381 0.80942495 0.68766928 0.02702219 0.46377415]]]


#### 4. Print *a*.


In [15]:
# Method 4
d = np.random.randint(2,3,5)
print(d)

[2 2 2 2 2]


In [61]:
# your code here
print(a)

[[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [62]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [63]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [68]:
# your code here
print(a.size)
print(b.size)
#different shape, same size

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [74]:
# your answer here
raise ValueError("operands could not be broadcast together with different shapes")
print(np.add(a,b))

ValueError: operands could not be broadcast together with different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [98]:
# your code here
print("original a\n", a)

c = b.transpose()
print("\ntranspose of b\n", c)

c_alvaro= b.reshape(2,3,5)
print("\nreshape of b\n", c_alvaro)

original a
 [[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]

transpose of b
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

reshape of b
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [99]:
# your code/answer here

#d = np.add(a,c)

d =np.add(a,c_alvaro)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [100]:
# your code/answer here
print("a\n", a)
print("\nd\n", d)

a
 [[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]

d
 [[[1.33921974 1.10322544 1.15622365 1.97971    1.03551493]
  [1.54195183 1.57410827 1.48526008 1.63073353 1.06376895]
  [1.1844261  1.77345612 1.3402157  1.97650945 1.15827595]]

 [[1.17050084 1.56486039 1.10257029 1.26953224 1.06532737]
  [1.35890909 1.38336053 1.55739284 1.1357     1.23930907]
  [1.13320925 1.77259133 1.03717997 1.87644653 1.09009858]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [101]:
# your code here
e = np.multiply(a,c_alvaro)
print(e)

[[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [102]:
# your code/answer here
print("a\n", a)
print("\ne\n", e)
print("\nthey are the same because we have mulitplied and devided by one and itself")

a
 [[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]

e
 [[[0.33921974 0.10322544 0.15622365 0.97971    0.03551493]
  [0.54195183 0.57410827 0.48526008 0.63073353 0.06376895]
  [0.1844261  0.77345612 0.3402157  0.97650945 0.15827595]]

 [[0.17050084 0.56486039 0.10257029 0.26953224 0.06532737]
  [0.35890909 0.38336053 0.55739284 0.1357     0.23930907]
  [0.13320925 0.77259133 0.03717997 0.87644653 0.09009858]]]

they are the same because we have mulitplied and devided by one and itself


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [114]:
# your code here
print("d\n",d,"\n")

d_max = np.max(d)
d_max2=d.max()
print("max: ",d_max," = ",d_max2)

d_min = np.amin(d)
print("min: ",d_min)
d_mean = np.mean(d)
print("mean: ",d_mean)

d
 [[[1.33921974 1.10322544 1.15622365 1.97971    1.03551493]
  [1.54195183 1.57410827 1.48526008 1.63073353 1.06376895]
  [1.1844261  1.77345612 1.3402157  1.97650945 1.15827595]]

 [[1.17050084 1.56486039 1.10257029 1.26953224 1.06532737]
  [1.35890909 1.38336053 1.55739284 1.1357     1.23930907]
  [1.13320925 1.77259133 1.03717997 1.87644653 1.09009858]]] 

max:  1.9797099983671682  =  1.9797099983671682
min:  1.0355149314306176
mean:  1.3699862681414603


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [119]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[1.33921974 1.10322544 1.15622365 1.97971    1.03551493]
  [1.54195183 1.57410827 1.48526008 1.63073353 1.06376895]
  [1.1844261  1.77345612 1.3402157  1.97650945 1.15827595]]

 [[1.17050084 1.56486039 1.10257029 1.26953224 1.06532737]
  [1.35890909 1.38336053 1.55739284 1.1357     1.23930907]
  [1.13320925 1.77259133 1.03717997 1.87644653 1.09009858]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [181]:
print(d)
# your code here
def values_to_f(f,d,d_min,d_max,d_mean):
    for i in range(2):
        for j in range(3):
            for k in range(5):
                if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                    f[i,j,k] = 25
                elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                    f[i,j,k] = 75
                elif d[i,j,k] == d_mean:
                    f[i,j,k] = 50
                elif d[i,j,k] == d_min:
                    f[i,j,k] = 0
                elif d[i,j,k] == d_max:
                    f[i,j,k] = 100
    

[[[1.33921974 1.10322544 1.15622365 1.97971    1.03551493]
  [1.54195183 1.57410827 1.48526008 1.63073353 1.06376895]
  [1.1844261  1.77345612 1.3402157  1.97650945 1.15827595]]

 [[1.17050084 1.56486039 1.10257029 1.26953224 1.06532737]
  [1.35890909 1.38336053 1.55739284 1.1357     1.23930907]
  [1.13320925 1.77259133 1.03717997 1.87644653 1.09009858]]]


In [182]:
values_to_f(f,d,d_min,d_max,d_mean)
print(f)

[[[ 25.  25.  25. 100.   0.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [183]:
# your code here
new_d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

new_d_max = np.max(new_d)
new_d_min = np.amin(new_d)
new_d_mean = np.mean(new_d)

new_f = np.empty([2,3,5])

def values_to_new_f(new_f,new_d,new_d_min,new_d_max,new_d_mean):
    for i in range(2):
        for j in range(3):
            for k in range(5):
                if new_d[i,j,k] > new_d_min and new_d[i,j,k] < new_d_mean:
                    new_f[i,j,k] = 25
                elif new_d[i,j,k] > new_d_mean and new_d[i,j,k] < new_d_max:
                    new_f[i,j,k] = 75
                elif new_d[i,j,k] == new_d_mean:
                    new_f[i,j,k] = 50
                elif new_d[i,j,k] == new_d_min:
                    new_f[i,j,k] = 0
                elif new_d[i,j,k] == new_d_max:
                    new_f[i,j,k] = 100

values_to_new_f(new_f,new_d,new_d_min,new_d_max,new_d_mean)
print(new_f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [184]:
#method 1
new_f_letters = np.empty([2,3,5], dtype=str)
def values_to_new_f(new_f_letters,new_d,new_d_min,new_d_max,new_d_mean):
    for i in range(2):
        for j in range(3):
            for k in range(5):
                if new_d[i,j,k] > new_d_min and new_d[i,j,k] < new_d_mean:
                    new_f_letters[i,j,k] = "B"
                elif new_d[i,j,k] > new_d_mean and new_d[i,j,k] < new_d_max:
                    new_f_letters[i,j,k] = "D"
                elif new_d[i,j,k] == new_d_mean:
                    new_f_letters[i,j,k] = "C"
                elif new_d[i,j,k] == new_d_min:
                    new_f_letters[i,j,k] = "A"
                elif new_d[i,j,k] == new_d_max:
                    new_f_letters[i,j,k] = "E"
values_to_new_f(new_f_letters,new_d,new_d_min,new_d_max,new_d_mean)
print(new_f_letters)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]


In [185]:
#method 2
new_f_letters = np.chararray([2,3,5])
def values_to_new_f(new_f_letters,new_d,new_d_min,new_d_max,new_d_mean):
    for i in range(2):
        for j in range(3):
            for k in range(5):
                if new_d[i,j,k] > new_d_min and new_d[i,j,k] < new_d_mean:
                    new_f_letters[i,j,k] = "B"
                elif new_d[i,j,k] > new_d_mean and new_d[i,j,k] < new_d_max:
                    new_f_letters[i,j,k] = "D"
                elif new_d[i,j,k] == new_d_mean:
                    new_f_letters[i,j,k] = "C"
                elif new_d[i,j,k] == new_d_min:
                    new_f_letters[i,j,k] = "A"
                elif new_d[i,j,k] == new_d_max:
                    new_f_letters[i,j,k] = "E"
values_to_new_f(new_f_letters,new_d,new_d_min,new_d_max,new_d_mean)
print(new_f_letters)

[[[b'D' b'D' b'D' b'B' b'D']
  [b'D' b'D' b'B' b'B' b'B']
  [b'D' b'B' b'D' b'D' b'D']]

 [[b'B' b'B' b'B' b'B' b'E']
  [b'D' b'D' b'D' b'D' b'D']
  [b'B' b'D' b'A' b'D' b'D']]]
