# NumPy (Numerical Python)

_It’s the universal standard for working with numerical data in Python!!!_

NumPy is the fundamental package for scientific computing in Python with a __large collection of high-level mathematical functions (i.e.: METHODS)__ to operate on these arrays. It is a Python library that provides a __multidimensional array OBJECT__.

https://numpy.org/doc/stable/

In [ ]:
#INSTALACION
#si ponemos "!" podemos instalar "conda install numpy" en vez de usar la terminal
#"!" te permite ejecutar una linea de la terminal
!conda install numpy
#!conda install numpy=1.20.2

Solving environment: ...working... done

# All requested packages already installed.



In [ ]:
# import library and assign an alias

import numpy as np
print(np.__version__)
type(np)

1.21.2


module

Numpy API Reference: https://numpy.org/doc/stable/reference/index.html#

---

__Array Object Attributes__

In [ ]:
# ndarray object attributes (https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes)

n_d_array = np.array([[1,2,3],[4,5,6]])

print(n_d_array, end='\n\n')
print(type(n_d_array))

print(n_d_array.ndim)   # number of array dimensions
print(n_d_array.shape)   # matrix's dimenssions size (i, j)
print(n_d_array.size)   # data buffer (i.e.: number of elements in the array)

print(n_d_array.dtype)   # https://numpy.org/doc/stable/reference/arrays.dtypes.html

print(n_d_array.itemsize)   # length of one array element in bytes 

[[1 2 3]
 [4 5 6]]

<class 'numpy.ndarray'>
2
(2, 3)
6
int32
4


In [ ]:
print(n_d_array.itemsize)   # length of one array element in bytes 

4


Further reading about array objects: https://numpy.org/doc/stable/reference/arrays.html

---

__Array Object Methods__ (https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-methods)

In [ ]:
# Array conversion => .copy() --> Return a copy of the array.

copy = n_d_array.copy()
copy

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Array conversion => .tolist() --> Return the array as an a.ndim-levels deep nested list of Python scalars.

py_list = n_d_array.tolist()
py_list

[[1, 2, 3], [4, 5, 6]]

In [ ]:
# Array conversion => .fill() --> Fill the array with a scalar value.

n_d_array.fill(8)
n_d_array

array([[8, 8, 8],
       [8, 8, 8]])

---

In [ ]:
# Shape manipulation => .reshape() --> Returns an array containing the same data with a new shape.

reshaped = n_d_array.reshape(3,2)
reshaped

array([[8, 8],
       [8, 8],
       [8, 8]])

In [ ]:
# Shape manipulation => .transpose() --> Returns a view of the array with axes transposed.

transposed = reshaped.transpose()
transposed

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
# Shape manipulation => .flatten() --> Return a copy of the array collapsed into one dimension.

flattened = n_d_array.flatten()
flattened

array([8, 8, 8, 8, 8, 8])

---

In [ ]:
# Calculation => .max() --> Return the maximum along a given axis.

max_ = n_d_array.max()
max_

8

In [ ]:
#por eje
max_ = n_d_array.max(axis=0)
max_

array([8, 8, 8])

In [ ]:
# Calculation => .max( --> Returns the indices of the maximum values along an axis.

argmax_ = n_d_array.argmax()
argmax_

0

In [ ]:
#por eje
argmax_ = n_d_array.argmax(axis=0)
argmax_

array([0, 0, 0], dtype=int64)

In [ ]:
# Calculation => .sum() --> Sum of array elements over a given axis.

sum_ = n_d_array.sum()
sum_

48

---

__Array creation routines__

In [ ]:
# numpy.arange() --> Return evenly spaced values within a given interval.

array_range = np.arange(2,8)
array_range

array([2, 3, 4, 5, 6, 7])

In [ ]:
# numpy.ones() --> Return a new array of given shape and type, filled with ones.

ones_array = np.ones((2,6))
ones_array
#pone un punto después de 1 pq es un float

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# numpy.zeros() --> Return a new array of given shape and type, filled with zeros.

zeros_array = np.zeros((2,7))
zeros_array
#pone un punto después de 1 pq es un float

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

---

## Indexing

![Image](./img/etl_numpy_01.png)



![Image](./img/etl_numpy_03.jpg)

In [ ]:
d1_array = np.arange(12)
d1_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

![Image](./img/etl_numpy_07.PNG)

In [ ]:
d2_array = d1_array.reshape((3,4))
d2_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

![Image](./img/etl_numpy_08.PNG)

In [ ]:
d3_array = d2_array.reshape((2,3,2))
d3_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

![Image](./img/etl_numpy_05.png)

In [ ]:
d3_array = np.zeros((3,3,3)) + 10
d3_array

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [ ]:
dn_array = np.arange(0,12).reshape((1,2, 1, 6, 1))
dn_array
#geométricamente se ha añadido una diemensión ás, a nivel analítico habrá una menos.
#para calcular hay que empezar por un corchete en adelante.

array([[[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]]],


        [[[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]]])

![Image](./img/etl_numpy_09.PNG)

In [ ]:
dn_array[0,1,0,5,0] #para ver el valor que está en esa posición

11

## Slicing

![Image](./img/etl_numpy_02.png)

In [ ]:
# Slicing (3,3)

slicing_array_3_3 = np.random.rand(3,3)
print(slicing_array_3_3)

slicing_array_3_3[:2,1:]

[[0.32565241 0.71635649 0.31758953]
 [0.69870177 0.10801026 0.17690796]
 [0.18389217 0.06067152 0.07447611]]


array([[0.71635649, 0.31758953],
       [0.10801026, 0.17690796]])

![Image](./img/etl_numpy_04.png)

In [ ]:
# Slicing deep_dive (6,6)

slicing_array_6_6 



SyntaxError: invalid syntax (Temp/ipykernel_2644/2801135836.py, line 3)

---

__More info:__ https://numpy.org/doc/stable/user/absolute_beginners.html

In [ ]:
hhh = np.random.random((10,4))
print(hhh)

In [ ]:
print(hhh[0])

In [ ]:
print(hhh[1:3,0])

In [ ]:
print(hhh[4,2])

In [ ]:
c = np.random.random((2,3,4,5))
print(c)

In [ ]:
print(c[0])

In [ ]:
print(c[0,1])

In [ ]:
print(c[0,1,2])

In [ ]:
print(c[0,1,2:4])

In [ ]:
print(c[0,:,2:4,4])

In [ ]:
a = c[0,:,2:4,4].shape
a